"""Interaction logging for the reflection system."""

import json
import os
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional
from uuid import UUID

from .models import InteractionLog, TaskResult


class ReflectionLogger:
    """Logger for recording AI interactions.
    
    This class handles recording interactions to disk for later reflection
    and analysis. It supports automatic organization by date and session.
    
    Example:
        >>> logger = ReflectionLogger()
        >>> log_id = logger.log_interaction(
        ...     task_description="Review Python code",
        ...     user_input="Check this function for bugs",
        ...     ai_output="The function looks correct",
        ...     result="partial",
        ...     user_feedback="Missed a null pointer issue"
        ... )
    """
    
    def __init__(self, storage_path: Optional[str] = None):
        """Initialize the logger.
        
        Args:
            storage_path: Base path for storing logs. Defaults to ~/.mechforge/reflections
        """
        if storage_path is None:
            storage_path = os.path.expanduser("~/.mechforge/reflections")
        self.storage_path = Path(storage_path)
        self.interactions_path = self.storage_path / "interactions"
        self._ensure_directories()
        
    def _ensure_directories(self) -> None:
        """Create necessary directories if they don't exist."""
        self.interactions_path.mkdir(parents=True, exist_ok=True)
        
    def log_interaction(
        self,
        task_description: str,
        user_input: str,
        ai_output: str,
        result: str = "unknown",
        task_type: str = "general",
        session_id: Optional[str] = None,
        user_feedback: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None,
        duration_ms: Optional[int] = None,
    ) -> UUID:
        """Log a single interaction.
        
        Args:
            task_description: Brief description of the task
            user_input: The input received from user
            ai_output: The output generated by AI
            result: Task result (success/partial/failure/unknown)
            task_type: Category of task
            session_id: Optional session identifier
            user_feedback: Optional user feedback
            metadata: Additional metadata
            duration_ms: Task duration in milliseconds
            
        Returns:
            UUID of the created log entry
        """
        log = InteractionLog(
            task_description=task_description,
            user_input=user_input,
            ai_output=ai_output,
            result=TaskResult(result),
            task_type=task_type,
            session_id=session_id,
            user_feedback=user_feedback,
            metadata=metadata or {},
            duration_ms=duration_ms,
        )
        
        # Store in date-organized directory
        date_str = log.timestamp.strftime("%Y-%m-%d")
        date_dir = self.interactions_path / date_str
        date_dir.mkdir(exist_ok=True)
        
        file_path = date_dir / f"{log.id}.json"
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(log.model_dump(), f, indent=2, ensure_ascii=False)
            
        return log.id
    
    def get_log(self, log_id: UUID) -> Optional[InteractionLog]:
        """Retrieve a specific log entry.
        
        Args:
            log_id: UUID of the log to retrieve
            
        Returns:
            The InteractionLog if found, None otherwise
        """
        # Search through date directories
        for date_dir in self.interactions_path.iterdir():
            if date_dir.is_dir():
                file_path = date_dir / f"{log_id}.json"
                if file_path.exists():
                    with open(file_path, "r", encoding="utf-8") as f:
                        data = json.load(f)
                        return InteractionLog(**data)
        return None
    
    def get_recent_logs(
        self,
        limit: int = 10,
        task_type: Optional[str] = None,
        result: Optional[str] = None,
    ) -> list[InteractionLog]:
        """Get recent log entries with optional filtering.
        
        Args:
            limit: Maximum number of logs to return
            task_type: Filter by task type
            result: Filter by result status
            
        Returns:
            List of matching InteractionLog entries
        """
        logs = []
        
        # Iterate through date directories (newest first)
        date_dirs = sorted(self.interactions_path.iterdir(), reverse=True)
        
        for date_dir in date_dirs:
            if not date_dir.is_dir():
                continue
                
            # Get files in this directory (newest first by mtime)
            files = sorted(
                date_dir.glob("*.json"),
                key=lambda p: p.stat().st_mtime,
                reverse=True,
            )
            
            for file_path in files:
                with open(file_path, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    log = InteractionLog(**data)
                    
                    # Apply filters
                    if task_type and log.task_type != task_type:
                        continue
                    if result and log.result.value != result:
                        continue
                        
                    logs.append(log)
                    
                    if len(logs) >= limit:
                        return logs
                        
        return logs
    
    def update_feedback(
        self,
        log_id: UUID,
        feedback: str,
        result: Optional[str] = None,
    ) -> bool:
        """Update a log entry with user feedback.
        
        Args:
            log_id: UUID of the log to update
            feedback: User feedback text
            result: Optional result override
            
        Returns:
            True if update was successful
        """
        log = self.get_log(log_id)
        if log is None:
            return False
            
        log.user_feedback = feedback
        if result:
            log.result = TaskResult(result)
            
        # Find and update the file
        for date_dir in self.interactions_path.iterdir():
            if date_dir.is_dir():
                file_path = date_dir / f"{log_id}.json"
                if file_path.exists():
                    with open(file_path, "w", encoding="utf-8") as f:
                        json.dump(log.model_dump(), f, indent=2, ensure_ascii=False)
                    return True
                    
        return False
    
    def get_stats(self) -> Dict[str, Any]:
        """Get statistics about logged interactions.
        
        Returns:
            Dictionary with statistics
        """
        total = 0
        by_result = {"success": 0, "partial": 0, "failure": 0, "unknown": 0}
        by_type: Dict[str, int] = {}
        
        for date_dir in self.interactions_path.iterdir():
            if not date_dir.is_dir():
                continue
                
            for file_path in date_dir.glob("*.json"):
                with open(file_path, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    total += 1
                    by_result[data.get("result", "unknown")] += 1
                    task_type = data.get("task_type", "general")
                    by_type[task_type] = by_type.get(task_type, 0) + 1
                    
        return {
            "total_interactions": total,
            "by_result": by_result,
            "by_type": by_type,
        }
