import { useState, useEffect, useRef } from "react";
import BootLine from "../components/BootLine";
import ChatParticles from "../components/ChatParticles";
import MascotWhale from "../components/MascotWhale";

const BOOT_LINES = [
  { text: "[21:04] SYSTEM: Initializing MechForge AI...", color: "#c8d8e0", delay: 0 },
  { text: "> AI Assistant Ready", color: "#00e5ff", delay: 600 },
  { text: "Model: qwen2.5:3b", color: "#00e5ff", label: "Model", delay: 1000 },
  { text: "RAG Status: Active", color: "#00e5ff", label: "RAG Status", delay: 1200 },
  { text: "API: Ollama", color: "#00e5ff", label: "API", delay: 1400 },
  { text: "Memory: 42 KB", color: "#00e5ff", label: "Memory", delay: 1600 },
  { text: "Awaiting input...", color: "#c8d8e0", delay: 2000 },
];

const AIAssistant = () => {
  const [visibleLines, setVisibleLines] = useState([]);
  const [input, setInput] = useState("");
  const [messages, setMessages] = useState([]);
  const [blinkOn, setBlinkOn] = useState(true);
  const [booted, setBooted] = useState(false);
  const outputRef = useRef(null);

  // 启动动画
  useEffect(() => {
    BOOT_LINES.forEach((line, i) => {
      setTimeout(() => {
        setVisibleLines((prev) => [...prev, i]);
        if (i === BOOT_LINES.length - 1) setBooted(true);
      }, line.delay);
    });
  }, []);

  // 光标闪烁
  useEffect(() => {
    const t = setInterval(() => setBlinkOn((b) => !b), 530);
    return () => clearInterval(t);
  }, []);

  // 自动滚动
  useEffect(() => {
    if (outputRef.current)
      outputRef.current.scrollTop = outputRef.current.scrollHeight;
  }, [messages, visibleLines]);

  const handleSend = () => {
    if (!input.trim()) return;
    const now = new Date();
    const time = `[${String(now.getHours()).padStart(2, "0")}:${String(
      now.getMinutes()
    ).padStart(2, "0")}]`;
    setMessages((prev) => [...prev, { type: "user", text: input, time }]);
    const query = input;
    setInput("");
    setTimeout(() => {
      setMessages((prev) => [
        ...prev,
        {
          type: "ai",
          time,
          text: `Processing query: "${query}"\n> Analysis complete. RAG retrieval active.\nResponse generated by qwen2.5:3b.`,
        },
      ]);
    }, 800);
  };

  return (
    <>
      <div
        ref={outputRef}
        style={{
          flex: 1,
          padding: "20px 24px",
          overflowY: "auto",
          position: "relative",
          zIndex: 1,
          fontSize: 13,
          lineHeight: 1.6,
          background: "rgba(13, 17, 23, 0.2)",
        }}
      >
        {/* 聊天区域粒子背景 */}
        <ChatParticles />
        
        {/* 吉祥物鲸鱼 - 右下角装饰 */}
        <MascotWhale />
        
        {/* 聊天内容 - 确保在粒子和吉祥物之上 */}
        <div style={{ position: "relative", zIndex: 2 }}>
          {BOOT_LINES.map((line, i) => (
            <BootLine key={i} line={line} visible={visibleLines.includes(i)} />
          ))}
          {booted && (
            <div
              style={{
                height: 1,
                background: "linear-gradient(90deg, #00e5ff33, transparent)",
                marginBlock: 12,
              }}
            />
          )}
          {messages.map((msg, i) => (
            <div key={i} style={{ marginBottom: 6 }}>
              {msg.type === "user" ? (
                <div style={{ color: "#c8d8e0", fontSize: 13 }}>
                  <span style={{ color: "#3a6070" }}>{msg.time} </span>
                  <span style={{ color: "#00e5ff" }}>&gt; </span>
                  {msg.text}
                </div>
              ) : (
                <div
                  style={{
                    color: "#8ab4c8",
                    fontSize: 13,
                    paddingLeft: 16,
                    borderLeft: "2px solid #00e5ff33",
                    lineHeight: 1.6,
                  }}
                >
                  {msg.text.split("\n").map((l, j) => (
                    <div key={j}>
                      {l.startsWith(">") ? (
                        <span style={{ color: "#00e5ff" }}>{l}</span>
                      ) : (
                        l
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          ))}
          {booted && (
            <div
              style={{
                display: "inline-block",
                width: 8,
                height: 14,
                background: blinkOn ? "#00e5ff" : "transparent",
                marginTop: 4,
                verticalAlign: "middle",
              }}
            />
          )}
        </div>
      </div>

      <div
        style={{
          padding: "12px 20px",
          borderTop: "1px solid rgba(0, 229, 255, 0.15)",
          position: "relative",
          zIndex: 1,
          background: "rgba(13, 17, 23, 0.7)",
          backdropFilter: "blur(10px)",
          WebkitBackdropFilter: "blur(10px)",
        }}
      >
        <div
          style={{
            display: "flex",
            gap: 12,
            alignItems: "center",
            background: "rgba(17, 24, 32, 0.8)",
            borderRadius: 24,
            border: "1px solid rgba(0, 229, 255, 0.2)",
            padding: "6px 6px 6px 20px",
          }}
        >
          <input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && handleSend()}
            placeholder="输入工程问题，例如：计算M12螺栓的预紧力..."
            style={{
              flex: 1,
              background: "transparent",
              border: "none",
              outline: "none",
              color: "#c8d8e0",
              fontSize: 14,
              caretColor: "#00e5ff",
            }}
          />
          <button
            onClick={handleSend}
            style={{
              padding: "10px 24px",
              borderRadius: 20,
              border: "none",
              cursor: "pointer",
              background: "linear-gradient(135deg, #00b8d4, #0097a7)",
              color: "#fff",
              fontSize: 13,
              fontWeight: 600,
              display: "flex",
              alignItems: "center",
              gap: 6,
              boxShadow: "0 0 16px rgba(0,183,212,0.4)",
              transition: "all 0.2s",
            }}
            onMouseEnter={(e) =>
              (e.currentTarget.style.boxShadow =
                "0 0 24px rgba(0,229,255,0.6)")
            }
            onMouseLeave={(e) =>
              (e.currentTarget.style.boxShadow =
                "0 0 16px rgba(0,183,212,0.4)")
            }
          >
            <svg viewBox="0 0 24 24" width="14" height="14" fill="white">
              <path d="M2 21l21-9L2 3v7l15 2-15 2z" />
            </svg>
            发送
          </button>
        </div>
      </div>
    </>
  );
};

export default AIAssistant;
