/**
 * APIClient - HTTP API 客户端模块
 * 封装与后端的 HTTP 通信
 * 支持直接调用（桌面模式）和 HTTP 模式
 */

class APIClient {
  constructor(baseURL = null) {
    // 自动检测 API 地址：优先使用当前页面的 origin
    if (baseURL) {
      this.baseURL = baseURL;
    } else if (window.location.protocol === 'file:') {
      // 本地文件模式，使用默认地址
      this.baseURL = 'http://localhost:5000/api';
    } else {
      // HTTP 模式，使用当前页面的 origin
      this.baseURL = `${window.location.origin}/api`;
    }
    this.defaultHeaders = {
      'Content-Type': 'application/json'
    };
    // 检测是否为本地文件模式
    this.isLocalFile = window.location.protocol === 'file:';
  }

  /**
   * 发送请求
   * @param {string} endpoint - API 端点
   * @param {object} options - 请求选项
   * @returns {Promise}
   */
  async request(endpoint, options = {}) {
    const url = `${this.baseURL}${endpoint}`;
    const config = {
      ...options,
      headers: {
        ...this.defaultHeaders,
        ...options.headers
      }
    };

    try {
      const response = await fetch(url, config);

      // 处理非 JSON 响应
      const contentType = response.headers.get('content-type');
      if (!contentType || !contentType.includes('application/json')) {
        if (!response.ok) {
          throw new Error(`HTTP ${response.status}: ${response.statusText}`);
        }
        return response.text();
      }

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || data.message || `HTTP ${response.status}`);
      }

      return data;
    } catch (error) {
      console.error(`API request failed: ${endpoint}`, error);
      throw error;
    }
  }

  /**
   * GET 请求
   */
  get(endpoint, params = {}) {
    const queryString = new URLSearchParams(params).toString();
    const url = queryString ? `${endpoint}?${queryString}` : endpoint;
    return this.request(url, { method: 'GET' });
  }

  /**
   * POST 请求
   */
  post(endpoint, data = {}) {
    return this.request(endpoint, {
      method: 'POST',
      body: JSON.stringify(data)
    });
  }

  /**
   * PUT 请求
   */
  put(endpoint, data = {}) {
    return this.request(endpoint, {
      method: 'PUT',
      body: JSON.stringify(data)
    });
  }

  /**
   * DELETE 请求
   */
  delete(endpoint) {
    return this.request(endpoint, { method: 'DELETE' });
  }

  // ==================== AI Chat API ====================

  /**
   * 发送聊天消息
   * @param {string} message - 用户消息
   * @param {object} options - 选项 (rag, stream, context)
   */
  async sendChat(message, options = {}) {
    // 本地文件模式 - 返回模拟响应
    if (this.isLocalFile) {
      return this.getLocalResponse(message, options);
    }
    return this.post('/chat', {
      message,
      ...options
    });
  }

  // 本地模式下的模拟响应
  getLocalResponse(message, options = {}) {
    const responses = [
      `Processing query: "${message}"\n> Analysis complete. RAG retrieval ${options.rag ? 'active' : 'inactive'}.\nResponse generated by qwen2.5:3b.`,
      `Analyzing your request: "${message}"\n> Context retrieved from knowledge base.\nGenerating response...`,
      `Query received: "${message}"\n> Searching relevant information...\nResults found and synthesized.`,
      `Your query "${message}" has been processed.\n> Engaging AI model for response...\nDone.`
    ];
    const response = responses[Math.floor(Math.random() * responses.length)];
    return Promise.resolve({
      response,
      model: 'qwen2.5:3b',
      rag_used: options.rag || false
    });
  }

  /**
   * 流式聊天 (如果后端支持)
   */
  async *streamChat(message, options = {}) {
    const url = `${this.baseURL}/chat/stream`;
    const response = await fetch(url, {
      method: 'POST',
      headers: this.defaultHeaders,
      body: JSON.stringify({ message, ...options })
    });

    if (!response.ok) {
      throw new Error(`Stream request failed: ${response.status}`);
    }

    const reader = response.body.getReader();
    const decoder = new TextDecoder();

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      const chunk = decoder.decode(value);
      const lines = chunk.split('\n').filter(line => line.trim());

      for (const line of lines) {
        if (line.startsWith('data: ')) {
          const data = line.slice(6);
          if (data === '[DONE]') return;
          yield JSON.parse(data);
        }
      }
    }
  }

  /**
   * 获取对话历史
   */
  async getHistory() {
    return this.get('/chat/history');
  }

  /**
   * 清空对话历史
   */
  async clearHistory() {
    return this.delete('/chat/history');
  }

  // ==================== RAG API ====================

  /**
   * 搜索知识库
   * @param {string} query - 查询内容
   * @param {number} limit - 返回数量
   */
  async searchKnowledge(query, limit = 5) {
    // 本地文件模式 - 返回模拟结果
    if (this.isLocalFile) {
      const results = Array.from({ length: Math.min(limit, 3) }, (_, i) => ({
        title: `Result ${i + 1} for "${query}"`,
        content: `This is a simulated knowledge base result for the query: ${query}. In a real implementation, this would connect to the RAG engine.`,
        score: 0.95 - (i * 0.1),
        source: 'knowledge_base'
      }));
      return Promise.resolve(results);
    }
    return this.post('/rag/search', { query, limit });
  }

  /**
   * 获取 RAG 状态
   */
  async getRAGStatus() {
    // 本地文件模式
    if (this.isLocalFile) {
      return Promise.resolve({
        enabled: true,
        backend: 'local',
        doc_count: 0
      });
    }
    return this.get('/rag/status');
  }

  /**
   * 切换 RAG 开关
   */
  async toggleRAG(enabled) {
    // 本地文件模式
    if (this.isLocalFile) {
      return Promise.resolve({ enabled });
    }
    return this.post('/rag/toggle', { enabled });
  }

  // ==================== Config API ====================

  /**
   * 获取配置
   */
  async getConfig() {
    // 本地文件模式
    if (this.isLocalFile) {
      return Promise.resolve({
        ai: { provider: 'ollama', model: 'qwen2.5:3b' },
        rag: { enabled: true, backend: 'local', top_k: 5 },
        ui: { theme: 'dark', language: 'zh-CN' }
      });
    }
    return this.get('/config');
  }

  /**
   * 更新配置
   */
  async updateConfig(config) {
    // 本地文件模式
    if (this.isLocalFile) {
      return Promise.resolve({ success: true });
    }
    return this.post('/config', config);
  }

  /**
   * 获取可用模型列表
   */
  async getModels() {
    // 本地文件模式
    if (this.isLocalFile) {
      return Promise.resolve([
        { name: 'qwen2.5:3b', provider: 'ollama' },
        { name: 'llama3:8b', provider: 'ollama' },
        { name: 'gpt-4o', provider: 'openai' }
      ]);
    }
    return this.get('/models');
  }

  // ==================== Status API ====================

  /**
   * 获取系统状态
   */
  async getStatus() {
    // 本地文件模式
    if (this.isLocalFile) {
      return Promise.resolve({ status: 'ready', version: '0.5.0' });
    }
    return this.get('/status');
  }

  /**
   * 健康检查
   */
  async healthCheck() {
    try {
      const response = await fetch(`${this.baseURL}/health`, {
        method: 'GET',
        signal: AbortSignal.timeout(5000)
      });
      return response.ok;
    } catch {
      return false;
    }
  }
}

// 创建全局 API 客户端实例
const apiClient = new APIClient();

// 导出
window.APIClient = APIClient;
window.apiClient = apiClient;
